SELECT * FROM shift;
SELECT * FROM hourly;
SELECT * FROM monthly;
SELECT * FROM worker;
SELECT * FROM serves;
SELECT * FROM timeSpan;
SELECT * FROM services;
SELECT * FROM freelance;
SELECT * FROM person;
